export const REMOVE_ERROR = 'REMOVE_ERROR';

export const API_LOGIN_REQUEST = 'LOGIN_REQUEST';
export const API_LOGIN_REQUEST_SUCCEEDED = 'LOGIN_REQUEST_SUCCCEEDED';
export const API_LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';

export const API_UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const API_UPDATE_ORDER_REQUEST_SUCCEEDED = 'UPDATE_ORDER_REQUEST_SUCCCEEDED';
export const API_UPDATE_ORDER_REQUEST_FAILED = 'UPDATE_ORDER_REQUEST_FAILED';

export const API_FETCH_ACTIVE_ORDERS_REQUEST = 'FETCH_ACTIVE_ORDERS_REQUEST';
export const API_FETCH_ACTIVE_ORDERS_REQUEST_SUCCEEDED = 'FETCH_ACTIVE_ORDERS_REQUEST_SUCCCEEDED';
export const API_FETCH_ACTIVE_ORDERS_REQUEST_FAILED = 'FETCH_ACTIVE_ORDERS_REQUEST_FAILED';